# Block Drops
# Format: block-typ -> drop-id -> oraxen-item, chance (in %), min-amount, max-amount
block-drops:
  STONE:
    drop1:
      oraxen-item: "smooth_pebble"
      chance: 2.0  # 2% Chance
      min-amount: 1
      max-amount: 1

  DIAMOND_ORE:
    drop1:
      oraxen-item: "diamond_shard"
      chance: 25.0
      min-amount: 1
      max-amount: 3

  DEEPSLATE_DIAMOND_ORE:
    drop1:
      oraxen-item: "diamond_shard"
      chance: 30.0
      min-amount: 2
      max-amount: 4

  ANCIENT_DEBRIS:
    drop1:
      oraxen-item: "netherite_fragment"
      chance: 15.0
      min-amount: 1
      max-amount: 2

  OAK_LOG:
    drop1:
      oraxen-item: "resin"
      chance: 5.0
      min-amount: 1
      max-amount: 1